---
organizations:
  - name: Ecosystem
    id: "0"
    description: This organization is for the whole ecosystem
    isEcosystem: true
    sections:
      - name: Ecosystem Issues
        id: "0"
        url: http://www.isislab.it:3000/cs-data-provider/issues
        widgets:
          - type: channel
  - name: Demo CS-AWARE EU
    id: "4"
    description: The organization at https://demo.cs-aware.eu/index.html
    sections:
      - name: Incidents
        id: "13"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/graph
          - name: History
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/incidents/:id/table
          - type: channel
      - name: Policies
        id: "14"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/policies
        widgets:
          - name: Dos
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/policies/:id/dos
          - name: Don'ts
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/policies/:id/donts
          - type: channel
      - name: Stories
        id: "15"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/4/stories
        widgets:
          - name: Events
            type: timeline
            url: http://www.isislab.it:3000/cs-data-provider/organizations/4/stories/:id/timeline
          - type: channel
  - name: Organization X
    id: "1"
    description: This is the X organization
    sections:
      - name: Incidents
        id: "3"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/1/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/1/incidents/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/1/incidents/:id/graph
          - name: Observed Data
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/1/incidents/:id/table
          - type: channel
      - name: Policies
        id: "4"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/1/policies
        widgets:
          - name: Dos
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/1/policies/:id/dos
          - name: Don'ts
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/1/policies/:id/donts
          - type: channel
      - name: Stories
        id: "5"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/1/stories
        widgets:
          - name: Events
            type: timeline
            url: http://www.isislab.it:3000/cs-data-provider/organizations/1/stories/:id/timeline
          - type: channel
    widgets: []
  - name: Organization Y
    id: "2"
    description: This is the Y organization
    sections:
      - name: Incidents
        id: "6"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/2/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/2/incidents/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/2/incidents/:id/graph
          - name: Observed Data
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/2/incidents/:id/table
          - type: channel
      - name: Policies
        id: "7"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/2/policies
        widgets:
          - name: Dos
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/2/policies/:id/dos
          - name: Don'ts
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/2/policies/:id/donts
          - type: channel
      - name: Stories
        id: "8"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/2/stories
        widgets:
          - name: Events
            type: timeline
            url: http://www.isislab.it:3000/cs-data-provider/organizations/2/stories/:id/timeline
          - type: channel
    widgets: []
  - name: Organization Z
    id: "3"
    description: This is the Z organization
    sections:
      - name: Incidents
        id: "9"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/3/incidents
        widgets:
          - name: Description
            type: text-box
            url: http://www.isislab.it:3000/cs-data-provider/organizations/3/incidents/:id/text_box
          - name: System
            type: graph
            url: http://www.isislab.it:3000/cs-data-provider/organizations/3/incidents/:id/graph
          - name: Observed Data
            type: table
            url: http://www.isislab.it:3000/cs-data-provider/organizations/3/incidents/:id/table
          - type: channel
      - name: Policies
        id: "10"
        url: http://www.isislab.it:3000/cs-data-provider/organizations/3/policies
        widgets:
          - name: Dos
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/3/policies/:id/dos
          - name: Don'ts
            type: list
            url: http://www.isislab.it:3000/cs-data-provider/organizations/3/policies/:id/donts
          - type: channel
      - name: Stories
        id: "11"
        internal: true
        url: http://www.isislab.it:3000/cs-data-provider/organizations/3/stories
        widgets:
          - name: Events
            type: timeline
            url: http://www.isislab.it:3000/cs-data-provider/organizations/3/stories/:id/timeline
          - type: channel
    widgets: []
