---
organizations:
  - name: Ecosystem
    id: "0"
    description: This organization is for the whole ecosystem
    isEcosystem: true
    sections:
      - name: Ecosystem Issues
        id: "0"
        url: http://www.isislab.it:3000/cc-data-provider/issues
        widgets:
          - type: channel
  - name: IMF Climate Data
    id: "1"
    description: The organization at https://climatedata.imf.org/pages/climatechange-data
    sections:
      - name: Surface Temperature Change
        id: "10"
        url: http://www.isislab.it:3000/cc-data-provider/organizations/1/temperatures
        widgets:
          - name: World Change
            type: map
            url: http://www.isislab.it:3000/cc-data-provider/organizations/1/temperatures/:id/map?year=:year
          - type: channel
      - name: Atmospheric Carbon Dioxide Concentrations
        id: "11"
        url: http://www.isislab.it:3000/cc-data-provider/organizations/1/dioxide
        widgets:
          - name: World Concentrations
            type: map
            url: http://www.isislab.it:3000/cc-data-provider/organizations/1/dioxide/:id/map?year=:year
          - type: channel
      - name: Change In Mean Sea Levels
        id: "12"
        url: http://www.isislab.it:3000/cc-data-provider/organizations/1/seas
        widgets:
          - name: Sea Levels Change
            type: map
            url: http://www.isislab.it:3000/cc-data-provider/organizations/1/seas/:id/map?year=:year
          - type: channel
